fastavro/fastavro

fastavro/reader.py
tests/test_fastavro.py

This moves skip_sync to the end of the block (where the sync marker exists) rather than the start (where it will exist only when there was a previous block), and has it require the sync marker is present, and not try to handle the case where it isn't present. This means we no longer depend on seek, and can support streaming IO.
Fixes #39 for me.

Support streaming IO by removing need for seek in skip_sync

---

fastavro/writer.py

I'm using fastavro to write out large files (hundreds of mb+)
At that point the speed savings start becoming significant, but also I don't want to store the entire file in memory. Unfortunately the `writer()` api requires a list of records.
I refactored it to a class, with minimal changes. Unfortunately it requires that you call `.flush()` which is not an ideal api.

Refactor writer as optional class

---

fastavro/reader.py
fastavro/writer.py
tests/test_fastavro.py

ValueError is raised for nullable field

write None value for nullable field

---

fastavro/six.py
tests/test_logical_types.py

During the extended testing on the production data, I found an error in python 3+ :(
Sorry for the lack of testing.

leftmost bit decimal bug

---

README.md

Fix documentation on reader schema validation

---

ChangeLog
fastavro/__init__.py
fastavro/const.py
fastavro/reader.py
fastavro/writer.py
tests/test_logical_types.py

see https://github.com/tebeka/fastavro/issues/96

Fix logicalType date conversion

---

setup.py

@barrywhart Is this what you were referring to with the `extras_require`?

add ujson as an extras_require

---

fastavro/_writer.pyx
fastavro/_writer_py.py
fastavro/writer.py
tests/test_fastavro.py

Can I get some preliminary feedback on this PR? It implements the first idea discussed in #130.

For issue #130: Expose Writer class, add "dirty" property

---

fastavro/_reader.pyx
fastavro/_writer.pyx

Issue 128: Introduce descriptive ctypedefs for various-sized integer types

---

setup.py

Resolves https://github.com/tebeka/fastavro/issues/142

unpin cython version

---

.travis.yml
appveyor.yml
fastavro/__main__.py
fastavro/_six.pyx
fastavro/read.py
fastavro/six.py
tests/test_main_module.py

Resolves https://github.com/tebeka/fastavro/issues/148

test some of the fastavro __main__ functionality

---

fastavro/_read.pyx
tests/test_fastavro.py

Resolves https://github.com/tebeka/fastavro/issues/154

add windows test for doubles

---

README.md

I accidentally omitted the word "records" from a sentence...

Fix typo in earlier PR

---

fastavro/_write.pyx
fastavro/_write_py.py
tests/test_fastavro.py

Resolves https://github.com/tebeka/fastavro/issues/166

ensure strings are not treated as an array of strings

---

fastavro/_read.pyx
fastavro/_read_py.py
fastavro/_write.pyx
fastavro/_write_py.py
tests/test_logical_types.py

#179 #178
Made changes to solve Unknown logical types, also change the `prepare_uuid` to look for uuid.UUID instance.

Unknown Logical Types

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_fastavro.py
tests/test_schemaless.py

Resolves https://github.com/tebeka/fastavro/issues/176

allow for schema migration in the schemaless reader

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_aliases.py
tests/test_complex.py
tests/test_fastavro.py
tests/test_schemaless.py

Resolves https://github.com/tebeka/fastavro/issues/32

ensure records have a name field

---

.travis.yml
MANIFEST.in
appveyor.yml
developer_requirements.txt

Resolves https://github.com/tebeka/fastavro/issues/184

add developer requirements file

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_fastavro.py

Resolves https://github.com/tebeka/fastavro/issues/168

allow dict subclasses

---

fastavro/_read.pyx
tests/test_fastavro.py

Resolves https://github.com/tebeka/fastavro/issues/197

fix reader for large longs

---

fastavro/_validate_common.py
tests/test_validation.py

#210 fix the field to empty string issue in ValidationErrorData.__str__
also add a new unit test

Fix ValidationErrorData

---

LICENSE
MANIFEST.in

Resolves https://github.com/fastavro/fastavro/issues/222

add explicit MIT license file

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_aliases.py

Resolves https://github.com/fastavro/fastavro/issues/225

fix issue with aliases when there is a new field in the new schema

---

tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/155
One of the side effects of https://github.com/fastavro/fastavro/pull/237 is that it resolved https://github.com/fastavro/fastavro/issues/155 as well. However, I wanted to add a test for posterity.

ensure that a namespaced name must be used when writing with tuples

---

fastavro/_schema.pyx
fastavro/_schema_common.py
fastavro/_schema_py.py
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/206

ensure aliases are a list

---

fastavro/_schema.pyx

Resolves https://github.com/fastavro/fastavro/issues/196

use cdef and cpdef in _schema.pyx

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/244

fix issue where the reader schema wasn't getting parsed

---

.travis.yml
.travis_build_wheel.sh

Resolves https://github.com/fastavro/fastavro/issues/253

update travis to build mac wheels

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/265

fix namespace issue with embedded records

---

fastavro/_validation.pyx
fastavro/_validation_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/272

fix validator picking wrong union schema

---

fastavro/_validation.pyx
fastavro/_validation_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/274

union schema validation should still ignore extra fields

---

docs/reader.rst
fastavro/_read_py.py

Resolves https://github.com/fastavro/fastavro/issues/263

add more documentation for reader objects

---

fastavro/_six.pyx
fastavro/_write.pyx
fastavro/_write_py.py
fastavro/six.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/276
Should add documentation before merging.

add support for appending to files

---

fastavro/_read.pyx
fastavro/_read_py.py
fastavro/_write.pyx
fastavro/_write_py.py
tests/test_logical_types.py

Resolves https://github.com/fastavro/fastavro/issues/282

scale defaults to 0 if not specified

---

fastavro/_read_py.py
fastavro/_schema_py.py

Resolves https://github.com/fastavro/fastavro/issues/288

always parse the writer_schema when reading

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/295

ensure reader does not depend on tell API

---

fastavro/_write.pyx
fastavro/_write_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/300

add option for user to provide a sync_marker value

---

fastavro/_validation.pyx
fastavro/_validation_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/303

arrays should only validate against sequences, not iterables

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/246

add deprecation warning for `schema` attribute on the reader

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_promotion.py

Resolves https://github.com/fastavro/fastavro/issues/302

actually change the data type when promoting

---

fastavro/_validation.pyx
fastavro/_validation_py.py
tests/test_complex.py

see https://github.com/fastavro/fastavro/issues/309

Union UUID fix

---

fastavro/_validation.pyx
fastavro/_validation_py.py
tests/test_validation.py

Resolves https://github.com/fastavro/fastavro/issues/315

True and False should not validate as int, long, float, and double

---

fastavro/_read.pyx
fastavro/_schema.pyx
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/312

force read the writer schema in the cython implementation

---

appveyor.yml
fastavro/_validation.pyx
fastavro/_validation_py.py

Resolves https://github.com/fastavro/fastavro/issues/321

prevent error that will be in python 3.8

---

appveyor.yml

Resolves https://github.com/fastavro/fastavro/issues/328

add 32 bit builds of windows

---

fastavro/_validation.pyx
fastavro/_validation_py.py
fastavro/_write.pyx
fastavro/_write_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/336

more handling of nulls and unions

---

fastavro/_write.pyx
fastavro/_write_py.py
tests/test_logical_types.py

Resolves https://github.com/fastavro/fastavro/issues/334

accept an iso string date

---

.travis.yml
azure-pipelines.yml
tests/test_compression.py
tests/test_main_cli.py

Resolves https://github.com/fastavro/fastavro/issues/347

add tests for snappy

---

fastavro/_logical_writers.pyx
fastavro/_logical_writers_py.py
fastavro/_validation.pyx
fastavro/_validation_py.py
fastavro/_write.pyx
fastavro/_write_py.py
fastavro/logical_writers.py
fastavro/write.py
setup.py
tests/test_fastavro.py
tests/test_timezone.py

Attempt to fix the main issue in https://github.com/fastavro/fastavro/issues/173.

Prepare logical types in validation

---

fastavro/json_read.py
fastavro/json_write.py

The examples introduced in #343 were slightly broken.

Fix JSON reader / writer examples

---

fastavro/_six.pyx
fastavro/six.py

Resolves https://github.com/fastavro/fastavro/issues/358

buffer attribute is not part of the API and so we can not rely on it

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_schema_evolution.py

Resolves https://github.com/fastavro/fastavro/issues/363

match records within arrays

---

fastavro/_logical_writers.pyx
tests/conftest.py
tests/test_validation.py

Resolves https://github.com/fastavro/fastavro/issues/365

fix type error in cython implementation

---

.travis.yml
README.md
appveyor.yml
azure-pipelines.yml
publish.sh
setup.py
tox.ini

Resolves https://github.com/fastavro/fastavro/issues/372

support python 3.8

---

.travis.yml
README.md
azure-pipelines.yml
docs/index.rst
fastavro/_read.pyx
fastavro/_read_py.py
fastavro/_write.pyx
fastavro/_write_py.py
setup.py
tests/test_compression.py

Add support for `lz4` compression codec in `fastavro`

Add optional lz4 codec

---

fastavro/_write_py.py
fastavro/io/binary_encoder.py
fastavro/io/json_encoder.py
tests/test_json.py

Resolves https://github.com/fastavro/fastavro/issues/380

parser needs the map and array start even if there are no contents

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/383

fix return_record_name for named types

---

appveyor.yml
benchmark/benchmark.py
developer_requirements.txt
fastavro/_timezone.py
run-tests.sh
setup.py
tests/conftest.py
tests/test_logical_types.py
tests/test_timezone.py

I believe this should resolve https://github.com/gojek/feast/pull/490. Need to do a bit more testing to verify.

use pytz instead of our own version

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/393

retain doc field when parsing schema

---

fastavro/_schema.pyx
fastavro/_schema_py.py
fastavro/schema.py
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/378

add new public api to get the fullname of a schema

---

fastavro/_schema.pyx
fastavro/_schema_py.py
fastavro/schema.py
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/314

add option to expand schemas

---

fastavro/io/json_decoder.py
tests/test_json.py

Resolves https://github.com/fastavro/fastavro/issues/399

fix bug with unions inside of arrays

---

.travis.yml
README.md
azure-pipelines.yml
docs/index.rst
fastavro/_read.pyx
fastavro/_read_py.py
fastavro/_write.pyx
fastavro/_write_py.py
setup.py
tests/test_compression.py

Resolves https://github.com/fastavro/fastavro/issues/405

add support for the xz codec

---

developer_requirements.txt
tests/test_logical_types.py

Resolves https://github.com/fastavro/fastavro/issues/409

fix test comparing native and tz datetimes

---

.travis.yml
README.md
azure-pipelines.yml
developer_requirements.txt

Resolves https://github.com/fastavro/fastavro/issues/408

install most codecs in developer_requirements.txt

---

fastavro/_validation.pyx
fastavro/_validation_py.py
tests/test_validation.py

Resolves https://github.com/fastavro/fastavro/issues/416

always parse the schema when calling validate

---

fastavro/_write.pyx
fastavro/_write_py.py
fastavro/validation.py

Resolves https://github.com/fastavro/fastavro/issues/425

use internal _validate to prevent unneeded schema parsing

---

fastavro/_schema.pyx
fastavro/_schema_py.py
fastavro/_write.pyx
fastavro/_write_py.py
tests/test_fastavro.py
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/444

add hint to top level union schemas

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/load_schema_test/A.avsc
tests/load_schema_test/B.avsc
tests/load_schema_test/C.avsc
tests/load_schema_test/D.avsc
tests/load_schema_test_2/A.avsc
tests/load_schema_test_2/B.avsc
tests/load_schema_test_2/C.avsc
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/443

fix bug where load schema was creating unions of unions

---

fastavro/_logical_writers.pyx
fastavro/_logical_writers_py.py
tests/test_logical_types.py

Check actual decimal value precision during serialization

---

azure-pipelines.yml
benchmark/benchmark.py
fastavro/_read.pyx
fastavro/_read_py.py
fastavro/_schema.pyx
fastavro/_schema_common.py
fastavro/_schema_py.py
fastavro/_validation.pyx
fastavro/_validation_py.py
fastavro/_write.pyx
fastavro/_write_py.py
fastavro/io/json_decoder.py
fastavro/io/json_encoder.py
fastavro/io/parser.py
tests/conftest.py
tests/test_fastavro.py
tests/test_json.py
tests/test_schema.py
tests/test_schemaless.py
tests/test_validation.py

Resolves https://github.com/fastavro/fastavro/issues/450
This is a work in progress... We'll see how it goes.

do not use global SCHEMA_DEFS

---

fastavro/_logical_writers.pyx
fastavro/_logical_writers_py.py
fastavro/_read.pyx
fastavro/_read_py.py
tests/test_timezone.py

https://github.com/fastavro/fastavro/issues/458

fix timestamp-millis for problem cases

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_schema.py

Resolves #457:
- Added missing check for positiveness of scale and precision
- Added check for scale <= precision
- Added check for fixed type dicimal precision limit

Improved decimal schema validation

---

.github/workflows/build_mac.yml

Resolves: https://github.com/fastavro/fastavro/issues/395

test pypy3 on osx

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_schema_evolution.py

Resolves https://github.com/fastavro/fastavro/issues/486

fix bug with schema evolution in unions

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/load_schema_test_7/A.avsc
tests/load_schema_test_7/namespace.B.avsc
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/490

resolve namespaces when fixing schemas

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/load_schema_test_8/A.avsc
tests/load_schema_test_8/namespace.B.avsc
tests/load_schema_test_8/namespace.C.avsc
tests/load_schema_test_9/A.avsc
tests/load_schema_test_9/namespace.B.avsc
tests/load_schema_test_9/namespace.C.avsc
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/490

handle case where an enum or fixed is found but already resolved

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_fastavro.py
tests/test_json.py

Resolves https://github.com/fastavro/fastavro/issues/503

implement skip functions

---

fastavro/_write.pyx
fastavro/_write_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/509

fix bug in union writing with tuple notation

---

fastavro/_read.pyx
fastavro/_read_common.py
fastavro/_read_py.py
tests/test_aliases.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/512
Resolves https://github.com/fastavro/fastavro/issues/515

fix issue with resolving named types

---

docs/logical_types.rst
fastavro/_logical_writers.pyx
fastavro/_logical_writers_py.py
fastavro/_read.pyx
fastavro/_read_py.py
tests/test_logical_types.py

Resolves https://github.com/fastavro/fastavro/issues/354

add support for local-timestamp micros and millis

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_schema.py

538 fix schema expansion of parsed schemas

---

fastavro/_read.pyx
fastavro/_read_common.py
fastavro/_read_py.py
fastavro/_write.pyx
fastavro/_write_py.py
fastavro/const.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/536

be able to specify enum and fixed names in tuple writer

---

tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/537

add some tests

---

docs/writer.rst
fastavro/_validation.pyx
fastavro/_validation_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/540

add type hint to records

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_schema.py

Validate enum symbols.

---

fastavro/_write.pyx
fastavro/io/binary_encoder.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/556

errors with non string types should give a better message

---

fastavro/io/json_decoder.py
tests/test_json.py

Resolves https://github.com/fastavro/fastavro/issues/572

fix issue with json decoding of complex types within maps

---

fastavro/json_write.py
tests/test_json.py

Resolves https://github.com/fastavro/fastavro/issues/580

allow validator option in json_writer

---

fastavro/_write.pyx
fastavro/_write_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/422

supply None schema to append file

---

README.md

Hello! Was nice meeting you at Pycon. Just noticed some minor fixes to README when I passed by.

DOC: Minor README edits

---

.github/workflows/build_mac.yml
.github/workflows/build_windows.yml
.travis_build_wheel.sh
Makefile
README.md
publish.sh
pyproject.toml
run-tests.cmd
run-tests.sh
setup.py

Resolves https://github.com/fastavro/fastavro/issues/600

include pyproject.toml

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/601

fix bug where records should match but they were not

---

fastavro/_write.pyx
fastavro/_write_py.py
tests/load_schema_test_16/namespace.match.avsc
tests/load_schema_test_16/namespace.team.avsc
tests/test_fastavro.py
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/608

fix append bug

---

README.md
docs/logical_types.rst
docs/writer.rst
fastavro/_read_py.py
fastavro/_schema.pyx
fastavro/_schema_py.py
fastavro/_write.pyx
tests/test_appendable.py
tests/test_schema.py

fixed some spelling mistakes,

---

fastavro/_write.pyi
fastavro/_write.pyx
fastavro/_write_py.py
fastavro/json_write.py
tests/test_fastavro.py
tests/test_json.py
tests/test_schemaless.py

Resolves https://github.com/fastavro/fastavro/issues/549

add options for strict and strict_allow_default

---

fastavro/io/json_decoder.py
tests/test_json.py

Resolves https://github.com/fastavro/fastavro/issues/629

fix issue with decoding records within maps

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_schema_evolution.py

Resolves https://github.com/fastavro/fastavro/issues/553

fix issue where writer and reader schemas would collide

---

fastavro/_validation.pyi
fastavro/_validation.pyx
fastavro/_validation_py.py
tests/test_validation.py

Resolves https://github.com/fastavro/fastavro/issues/423

add strict option in validation

---

fastavro/_validation.pyx
fastavro/_validation_py.py
fastavro/_write.pyi
fastavro/_write.pyx
fastavro/_write_py.py
fastavro/json_write.py
tests/test_fastavro.py
tests/test_json.py
tests/test_schemaless.py

Resolves https://github.com/fastavro/fastavro/issues/548

add option to disable tuple notation

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_schema_evolution.py

Resolves https://issues.apache.org/jira/browse/AVRO-3622

records should match via their unqualified names

---

fastavro/_write.pyx
fastavro/_write_py.py
tests/test_fastavro.py
tests/test_json.py
tests/test_schemaless.py

Resolves https://github.com/fastavro/fastavro/issues/638

fix bug where strict options were not catching extra fields

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/663

allow ints as default values for floats

---

fastavro/_schema.pyx
fastavro/_schema_py.py
fastavro/_write.pyx
fastavro/_write_py.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/674

allow values like nan for float and double defaults

---

fastavro/json_read.py
tests/test_json.py

Resolves https://github.com/fastavro/fastavro/issues/669

be able to specify a reader schema in a json reader

---

fastavro/_schema.pyx
fastavro/_schema_py.py
tests/test_schema.py

Resolves https://github.com/fastavro/fastavro/issues/690

fix namespace handling

---

fastavro/_read.pyi
fastavro/_read.pyx
fastavro/_read_py.py
fastavro/io/binary_decoder.py
fastavro/io/json_decoder.py
tests/test_json.py
tests/test_schemaless.py

Resolves https://github.com/fastavro/fastavro/issues/695

ability to override unicode decode errors

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_fastavro.py
tests/test_match.py

https://github.com/fastavro/fastavro/issues/700

Allows referencing mentioned schema by name

---

fastavro/_read.pyx
fastavro/_read_py.py
fastavro/_schema.pyx
fastavro/_schema_py.py
fastavro/schema.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/543

add return_named_type and return_named_type_override

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_schema_evolution.py

Supersedes https://github.com/fastavro/fastavro/pull/655

Retoo feature/better errors

---

.gitignore
developer_requirements.txt
fastavro/_read.pyx
fastavro/_read_common.py
fastavro/_read_py.py
fastavro/_write.pyx
fastavro/_write_py.py
mypy.ini
tests/test_compression.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/682

allow cramjam

---

run-tests.cmd
tests/conftest.py
tests/test_compression.py
tests/test_fastavro.py
tests/test_logical_types.py

Resolves https://github.com/fastavro/fastavro/issues/643

make sure windows tests fail on error

---

.github/workflows/build_linux.yml
.github/workflows/build_mac.yml
.github/workflows/build_windows.yml
fastavro/_read.pyx
fastavro/_read_py.py
fastavro/_write.pyx
fastavro/_write_py.py
setup.py
tests/conftest.py
tests/test_compression.py
tests/test_fastavro.py

Resolves https://github.com/fastavro/fastavro/issues/722

add deprecation about using python-snappy

---

developer_requirements.txt
tests/test_block_reader.py

Resolves https://github.com/fastavro/fastavro/issues/740 and https://github.com/fastavro/fastavro/issues/605

test with zlibng

---

fastavro/_read.pyx
fastavro/_read_py.py
tests/test_aliases.py

Same as https://github.com/fastavro/fastavro/pull/749 but with additional tests. This should fix https://github.com/fastavro/fastavro/issues/648 (added test similar to the example).

Fix aliases in schema resolution

---

fastavro/utils.py

When using the `gen_many` function in `fastavro.utils` one would expect that every combination of enum values or union branches is generated at some point, if a lot of message are generated.
But for some schemas the function returns deterministic output. This seems to be caused by the usage of a incrementing index that is currently used to generate booleans, enums and union branches.
A example schema:
```
record MessageBranchA
{
string? optional_name;
}
enum SomeEnum
{
A, B
}
record MessageBranchB
{
SomeEnum e;
}
record Message
{
union {MessageBranchA, MessageBranchB} main_branch;
}
```
When generating random Message values, we will see:
* index 0 (%2 = 0): select MessageBranchA, set optional_name to null ( string? <=> union {null,string})
* index 1 (%2 = 1): select MessageBranchB, set …

Fix deterministic output for gen_many under certain conditions

---

fastavro/_read.pyi

Resolves https://github.com/fastavro/fastavro/issues/787

fix some of the type stubs

---

fastavro/types.py

Contributes to addressing https://github.com/fastavro/fastavro/issues/797

Parametrize some generic types to avoid type checker warnings
