- .travis.yml
- MANIFEST.in
- tox.ini
Without README.md, `pip install fastavro==0.8.2` fails:
```
Collecting fastavro>=0.7.8 (from internal-package==2.2.0->-r /tmp/requirements.txt (line 2))
Downloading fastavro-0.8.2.tar.gz (167kB)
Complete output from command python setup.py egg_info:
File "<string>", line 20, in <module>
File "/tmp/pip-build-e7z6XB/fastavro/setup.py", line 75, in <module>
long_description=open('README.md').read(),
IOError: [Errno 2] No such file or directory: 'README.md'
```
> Include README.md in packages and check packaging with travis/tox

- fastavro/reader.py
- fastavro/schema.py
- fastavro/six.py
- fastavro/writer.py
- tests/test_fastavro.py
Raise a `fastavro.schema.UnknownType` every time we try to use an unknown type definition (refer to a name we haven't defined yet, mostly).
> Detect unknown types

- fastavro/schema.py
- tests/test_fastavro.py
When you refer to a previously defined schema using an unqualified name, and there's an enclosing `namespace` to work with, we need to [join the two together](http://avro.apache.org/docs/current/spec.html#Names) to get the fully qualified name to look for — unless the unqualified name is one of the primitive types, in which case it should stay unqualified.
> Add enclosing namespace to unqualified references

- fastavro/writer.py
- tests/test_fastavro.py
If a field has a default value it's nice to have the writer go ahead and use that value when serializing (instead of throwing an error about the field missing).
> write the default value if the record has one

- fastavro/reader.py
- tests/test_fastavro.py
Hopefully no more boolean PRs... the previous PR was setting all booleans to True. Copying the associated test case and running it on master shows that.
Previously:
```python
In [22]: pack('B', 1) != 0x00
Out[22]: True
In [23]: pack('B', 0) != 0x00
Out[23]: True
```
Now:
```python
In [25]: unpack('B', pack('B', 1))[0] != 0
Out[25]: True
In [26]: unpack('B', pack('B', 0))[0] != 0
Out[26]: False
```
> correct boolean roundtrip

- fastavro/__init__.py
- fastavro/reader.py
- fastavro/schema.py
- fastavro/writer.py
Instead of populating both the READERS and WRITERS repo on any operation, only the relevant repo will be populated. For a very complex schema I noticed a 5-10% speed up in writing and a 10-20% speed up in reading.
> only populate the necessary repo

- fastavro/writer.py
In python2 `str is bytes` but in python 3 `str` won't do for fixed/bytes fields (and infact reader decodes as `bytes`)
> Fix writer.validate to look for bytes rather than str for a fixed or bytes field, ensuring it works with python 3

- fastavro/schema.py
- tests/test_fastavro.py
If a record name was already defined in the repo it would not be overwritten by a new record which would cause reads/writes to potentially fail (since they would use the original schema added to the repo)
> always overwrite repo values

- fastavro/writer.py
Small change - I think it seems right to reset the block count to zero whenever you do `writer.dump()` (whether through an auto-sync or a manual `flush()`). Otherwise `dump()` can be called with no available blocks, which seems to be bad.
> Fix block count corruption on writer.flush() after an auto-sync

- fastavro/writer.py
- tests/test_fastavro.py
Added an optional shortcut when outputting a union that allows the user to provide a tuple containing the name of the record.  
This is used to lookup the appropriate schema by name instead of performing validation on all options.
It is completely backwards compatible with existing Avro serialization, but allows faster union write if the user provides a tuple in the format of (name, record) instead of simply the record itself.
A first attempt at a solution for #68 
Sorry for the delay in the pull request.
Timing comparison:
Schema:
<details><summary>Click to expand</summary><p>
```
protocol test {
record a {
int a;
int b;
int c0;
}
record b {
int a;
int b;
int c1;
}
record c {
int a;
int b;
int c2;
}
record d {
int a;
int b;
int c3;
}
record e {
int a;
int b;
int c4;
}
record f {
int a; …
```
> Added an optional shortcut when outputting a union

- fastavro/reader.py
- fastavro/schema.py
- fastavro/six.py
- fastavro/writer.py
- tests/test_logical_types.py
date(int), timestamp-millis(long), timestamp-micros(long), decimal(bytes)
> avro 1.8 logical types support

- fastavro/writer.py
- tests/test_logical_types.py
```
schema_leftmost = {
"type": "bytes",
"logicalType": "decimal",
"precision": 18,
"scale": 6,
}
binary = serialize(schema_leftmost, b'\xd5F\x80') #write binary data without any transformations
data2 = deserialize(schema_leftmost, binary)
assert (Decimal("-2.80") == data2)
'''
> passthrough logical types for backwords compatibility

- fastavro/six.py
- tests/test_str_py3.py
Without this the test will result in this error:
```
ERROR: test_str_py3.test_py3_union_string_and_bytes
----------------------------------------------------------------------
File "/Users/scott/.virtualenvs/fastavro/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
self.test(*self.arg)
File "/Users/scott/git/scottbelden/fastavro/tests/test_str_py3.py", line 56, in test_py3_union_string_and_bytes
fastavro.writer(buf, schema, records)
File "/Users/scott/git/scottbelden/fastavro/fastavro/writer.py", line 584, in writer
output.write(record)
File "/Users/scott/git/scottbelden/fastavro/fastavro/writer.py", line 507, in write
write_data(self.io, record, self.schema)
File "/Users/scott/git/scottbelden/fastavro/fastavro/writer.py", line 402, in …
```
> fix writing unions of bytes or strings on py3

- ChangeLog
- fastavro/__init__.py
- fastavro/writer.py
- tests/test_complex.py
This bug appears when unions are used. Like a {"type": ["null", {"type": "long", "logicalType": "timestamp-micros"}]}
> Fix incorrect verification of datetime logical type

- fastavro/reader.py
- tests/test_logical_types.py
Fix deserializing logicalType timestamp-millis was storing millisecond  inside Python's datatime microsecond property.
> Fix deserializing logicalType timestamp-millis millisecond gotcha

- .gitignore
- fastavro/reader.py
- fastavro/writer.py
- tests/test_complex.py
- tests/test_logical_types.py
Some comments:
*  In ```tests/test_logical_types.py```, why was the schema for bytes decimal called ```schema_top```? There's also a test called ```test_top()```, which was just a copy of ```test_bytes_decimal()```. Can we rename the schema  ```schema_fixed_decimal``` and get rid of ```test_top()```?
* In ```reader.py```, the comment of function ```read_bytes_decimal()``` sounded like it was for fixed decimals, so I moved this comment to the new function ``` read_fixed_decimal()```, and reworded the comment in ```read_bytes_decimal()```.
Tested in 
* ```Python 3.5.2```
* ```Python 2.7.12```
FYI
.cache directory from pytest should probably be in .gitignore.
Happy to update based on comments.
> Added fixed decimal type (fix for #105)

- tests/test_types.py
Resolves https://github.com/tebeka/fastavro/issues/37
This test was turned off for 3.4 but it was suspected that it was a python bug causing the issue. Recent testing shows that this now passes on 3.4.
> turn on test for py3.4

- appveyor.yml
- fastavro/_reader.pyx
- fastavro/_writer.pyx
- run-tests.sh
- setup.cfg
- tests/test_logical_types.py
Resolves https://github.com/tebeka/fastavro/issues/125
Resolves https://github.com/tebeka/fastavro/issues/126
@barrywhart I needed to change some of the `long`s to `long long` as it seems that for windows a `long` is only 4 bytes whereas on linux it is 8 bytes (which was causing some tests to fail on windows). I wasn't sure if this was the best approach and thought you might have more experience here.
> add appveyor testing for windows

- fastavro/_writer.pyx
- fastavro/_writer_py.py
- tests/test_fastavro.py
This fixes https://github.com/tebeka/fastavro/issues/48 as @scottbelden suggested in https://github.com/tebeka/fastavro/issues/48#issuecomment-220317143 . I had to change return value of `writer.validate` from `bool` to `int` so it can specify the score of validation, i.e. number of fields that validated against given `schema`. Then in `write_union` the schema is chosen not only if the schema validates but the one with highest number of validated fields is chosen.
> Fix union schema resolution in writer

- benchmark/benchmark.py
- fastavro/_writer.pyx
This PR speeds up writing timestamps.
* Python 2.7-3.2: 10-15%
* Python 3.3 and later: 25-28%
This is a Cython-only improvement; it has no impact on pure Python (i.e. pypy).
> Speed up timestamp writes

- fastavro/__main__.py
- fastavro/_six.pyx
- fastavro/six.py
- tests/test_logical_types.py
This fixes a bug I noticed with the `fastavro` command-line tool dumping an Avro file: If `ujson` is not installed (i.e. if using the built-in `json` module), dumping an Avro file with any of the higher-level logical (Python) types crashes:
* `datetime`
* `date`
* `Decimal`
* `UUID`
This occurs because `json.dumps()` does not support those data types.
I fixed this by scanning each record after it is read but before it is dumped, converting those values to strings. I'm not sure there is a perfect fix here, but this seems reasonable.
Here's an example stack trace of the failure with a `datetime` value:
```
File "/Users/bhart/.pyenv/versions/fastavro-2.7.13/bin/fastavro", line 11, in <module>
load_entry_point('fastavro', 'console_scripts', 'fastavro')()
File …
```
> `fastavro` command-line tool crashes if data contains date or date/time values

- fastavro/_write.pyx
- tests/test_fastavro.py
Address #139.
We add a runtime check to `write_record()` and `write_map()`. For `dict`, use faster code. For other types, use equivalent but slower, generic code. There appears to be no meaningful impact on performance.
```
Before:
Writing 10000 records to one file...
... 10 runs averaged 0.00915930271149 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0144769668579 seconds
Writing 10000 records to one file...
... 10 runs averaged 0.0550956249237 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0886501789093 seconds
After:
Writing 10000 records to one file...
... 10 runs averaged 0.00916681289673 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0137780666351 seconds
Writing 10000 records to one file...
... 10 runs averaged …
```
> Handle records and maps that are OrderedDict rather than dict

- fastavro/_read.pyx
- tests/test_fastavro.py
Aliases allow a writer field to have a different name than the reader
field. Potentially, there may be multiple reader fields pointing to the
same writer field, and this is the biggest difficulty to implement
aliases. Fields are read only once from file, but they may need to be
validated multiple times. Files may be read only once because we do not
support "seek()" statements.
The approach we chose was to create a file reader with a cache. A
potential issue with this is for aliased fields that take a lot of
space. We try to mitigate this issue by resorting to in-memory storage
as infrequently as possible.
This should close issue #87.
EDIT: we no longer try to handle the case when multiple reader fields point to the same writer field.
> Add support for Avro aliases

- fastavro/_write.pyx
- fastavro/_write_py.py
- tests/test_fastavro.py
Hi,
I've noticed cool feature in `write_union` that allow to specify schema of records precisely instead of guessing based on parameters. However this does not allow to use acquainted schemata (because string is not record and therefore has no `name` to look for). I think that this change will increase possibility of the feature. Please take a look. I will be happy to change the code according to your suggestions.
P.S. : I didn't create issue, should I?
> Write union using tuple with schema name

- .travis_build_wheel.sh
- appveyor.yml
- publish.sh
- run-tests.sh
- setup.py
PR for #144: Follow the [recommendations for distributing Cython packages](http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules).
`setup.py` now checks for an environment variable `FASTAVRO_USE_CYTHON` when it runs. (Note: If it seems better, we could instead use a command-line option or some other technique.) Some techniques for using non-standard command-line options with `setup.py` are covered [here](https://stackoverflow.com/questions/677577/distutils-how-to-pass-a-user-defined-parameter-to-setup-py).
If the environment variable is set to `1` (which should be the case when running `setup.py develop` and during packaging/publishing), the library requires Cython and uses the `.pyx` files. If not set (which should be the case during …
> When installing from source package, use the included .c files

- publish.sh
This should prevent missing linux wheels, see https://github.com/tebeka/fastavro/issues/169
> Add checks for linux wheels to `publish.sh`

- fastavro/_read.pyx
- fastavro/_read_py.py
- fastavro/_timezone.py
- fastavro/_write.pyx
- fastavro/_write_py.py
- tests/conftest.py
- tests/test_complex.py
- tests/test_logical_types.py
- tests/test_timezone.py
Fix for Issue 171 (adding in tzaware datetime objects)
One thing to note is that the output Python datetime object is now TZ-aware. TZ-aware datetime objects can't be compared with TZ-naive objects, so some downstream users might have problems if they rely on datetime objects being TZ-naive. However, the code branch for a Python2.7 (i.e. no datetime.timestamp() method) remains unchanged for TZ-naive objects when serializing the object as a long for Avro encoding.
Also, sorry if I missed any prep for the PR, it seemed like the "Hacking" section was talking about after a PR to fastavro gets merged... so I didn't do any of those steps. Lemme know if there's stuff I need to do from that section.
> Fastavro 171 logical timestamp tz support

- fastavro/_validation.pyx
- fastavro/_validation_py.py
- tests/test_validation.py
Before this change, benchmarking spuriously fails:
```bash
./run-tests.sh
python benchmark/benchmark.py
```
```
Small - 1 rec - 100,000 runs
Writing 1 records to one file...
... 100000 runs averaged 2.65738511086e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 2.72266125679e-05 seconds
Validating 1 records from one file...
File "benchmark/benchmark.py", line 161, in <module>
valid = validater(schema, original_records, runs=num_runs)
File "benchmark/benchmark.py", line 28, in validater
valid = validate_many(records, schema)
File "fastavro/_validation.pyx", line 228, in fastavro._validation.validate_many
cpdef validate_many(records, schema, bint raise_errors=True):
File "fastavro/_validation.pyx", line 239, in …
```
> fix overzealous validation errors

- fastavro/__init__.py
- fastavro/_read.pyx
- fastavro/_read_py.py
- fastavro/read.py
- tag.sh
- tests/test_block_reader.py
- tests/test_fastavro.py
[Apache Beam is interested in using fastavro instead of apache/avro](https://issues.apache.org/jira/browse/BEAM-2810), but needs an interface like I've added here, for seeking to and reading individual record-blocks in a file.
[I've published this as `fastavro-blocks:0.19.5.4` to test.pypi.org](https://test.pypi.org/project/fastavro-blocks/0.19.5.4/) (cf. [`blocks-test-pypi` branch](https://github.com/ryan-williams/fastavro/tree/blocks-test-pypi), which has [a commit on top of this PR changing the name and version](https://github.com/ryan-williams/fastavro/commit/e602bddefea6e3a369ddbd5c3695cf3d700da586)), and [used that in a Beam branch here](https://github.com/ryan-williams/beam/tree/fastavro).
Presumably it can't go into Beam until it's in real pypi, so that will have to wait until the …
> add block_reader interface

- fastavro/_validation.pyx
- fastavro/_validation_py.py
- fastavro/schema.py
- tests/test_validation.py
When running the following snippet...
```python
my_schema = {
"fields": [
{
"name": "array",
"type": {
"type": "array",
"items": "string",
},
},
],
"namespace": "namespace",
"name": "test_validate_array",
"type": "record"
}
datum = {"array": [1]}
validate(datum, my_schema)
```
An exception with this message is produced:
```python
fastavro._validate_common.ValidationError: [
" is <1> of type <class 'int'> expected string"
]
```
This change will make sure the field name shows up correctly like so:
```python
fastavro._validate_common.ValidationError: [
"namespace.test_validate_array.array is <1> of type <class 'int'> expected string"
]
```
> fix field name when validating arrays

- fastavro/__init__.py
- fastavro/_read.pyx
- fastavro/_read_py.py
- fastavro/read.py
- fastavro/write.py
- tests/test_fastavro.py
These APIs are not documented and probably not useful in general. Using the normal `reader` and `writer` interface is the better way to go.
> remove load and dump APIs

- benchmark/benchmark.py
- docs/index.rst
- docs/schema.rst
- fastavro/__init__.py
- fastavro/_read.pyx
- fastavro/_read_py.py
- fastavro/_schema.pyx
- fastavro/_schema_common.py
- fastavro/_schema_py.py
- fastavro/_write.pyx
- fastavro/_write_py.py
- fastavro/read.py
- fastavro/schema.py
- fastavro/write.py
- tests/conftest.py
- tests/test_fastavro.py
- tests/test_schema.py
- tests/test_schemaless.py
Not done with this yet, but pretty happy with the results so far. The high level take away is the following:
* `acquaint_schema` is no more
* `parse_schema` has been added
* It's not necessary to call `parse_schema` beforehand, but doing so will make future operations with that parsed schema faster
This PR will replace https://github.com/fastavro/fastavro/pull/214
> implement a parse_schema function

- fastavro/__init__.py
- fastavro/_schema.pyx
- fastavro/_schema_py.py
- tests/avro-files/Child1.avsc
- tests/avro-files/Parent.avsc
- tests/test_fastavro.py
An `list.insert` call mistake, in '_schema._load_schema' function. Cause error when Parent schema has multiple user-define-type.
> fix issue #248

- fastavro/_validate_common.py
- tests/test_validation.py
Ensure that in python2.7 only ascii is returned from ValidationErrorData so that str(e) does not fail.
Resolves #269
> Fix failure in ValidationError class - Resolves Issue #269

- fastavro/_six.pyx
- fastavro/six.py
- tests/test_fastavro.py
- tests/test_six.py
- tox.ini
> Bugfix regression since 0.21.7: Allow writing to non-seekable streams again

- fastavro/_read.pyx
- fastavro/_read_py.py
- tests/test_fastavro.py
- tests/test_schema_evolution.py
See https://issues.apache.org/jira/browse/AVRO-1340
In Avro 1.9 (whenever it gets released) and enum schema will be able to have a `default` that can be used by the reader schema if the enum that was written doesn't exist in the reader's `symbol` list.
> add support for specifying a default value for enums (see AVRO-1340)

- .travis_build_wheel.sh
- publish.sh
We run `py27mu`, which requires installing via `.tar.gz` (and therefore
all the compilation dependencies are required as well). But we vastly
prefer the speed and simplicity of installing fastavro via wheel.
This change publishes a wheel for `py27mu`.
-----
The full list of distributions currently supported by the manylinux
image is:
```
$ docker run -it quay.io/pypa/manylinux1_x86_64 bash -c "ls /opt/python"
cp27-cp27m  cp27-cp27mu  cp34-cp34m  cp35-cp35m  cp36-cp36m  cp37-cp37m
```
All of these are currently published as wheels with the exception of
`cp27mu`.
I've tested this change by running this invocation from the `.travis.yml`:
```
$ docker run --rm -v "$(pwd):/data" quay.io/pypa/manylinux1_x86_64 bash -c "/data/.travis_build_wheel.sh 2.7 && ls /data/dist/"
... …
```
> Publish wheel for py27mu (in addition to py27m)

- fastavro/_read.pyx
- fastavro/_write.pyx
- fastavro/_write_py.py
- tests/test_block_reader.py
- tests/test_write_block.py
- tox.ini
This method is effectively a fast path for writing blocks with a matching schema to an OCF writer.
The primary use cases for this are very fast concatenation and recompressing existing OCF files, or doing both at once which is common in big data scenarios where you might want to combine many small files into one.
This could be additionally be exposed as a `block_writer` interface similar to `block_reader`
Note I have not added any safety checks as the system we are using this in already hashes the schemas of incoming OCF files before concatenating them but a similar approach could be added to the library (or warning labels added) - figured I would ask what you prefer.
Additionally this fixes up some small issues in separate commits, if you prefer I can move those into a different PR.
> Add Writer.write_block()

- fastavro/_write.pyx
- fastavro/_write_py.py
- tests/test_fastavro.py
This hopefully resolves [the issue raised in passing here](https://github.com/fastavro/fastavro/issues/312#issue-402769560) which is that we shouldn't be writing `__fastavro_parsed` to the datafile.
> do not write the hint to the datafile

- ChangeLog
- fastavro/__init__.py
- fastavro/__main__.py
- fastavro/_six.pyx
- fastavro/six.py
- tests/test_six.py
- tests/test_write_block.py
- Create a TDD in ``tests/test_six.py``, where it is necessary to temporarily
disable pytest's 'capfd' method, https://docs.pytest.org/en/latest/capture.html
- This test then fails, raising ValueError on OSX, and fixed by ``is sys.stdout`` identity check.
- To support this test, lazily bind to sys.stdout object reference in ``six.py`` (and ``_six.pyx``), we want sys.stdout reference at runtime rather than import, because we would otherwise get a handle of the "capfd" (file-like) stdout from pytest, even after disabling it our test.
- Unrelated but fun, use ``pytest.mark.parameterize()`` in ``tests/test_write_block.py``
Closes #330
> Fix Mac OSX Streaming output to sys.stdout.buffer (Closes #330).

- fastavro/_read_py.py
Resolves https://github.com/fastavro/fastavro/issues/345
- Snappy expects to get a file that has method
`read` but actually gets passed a decoder that
has no generic `read` method
- Fix is to change `read` to `read_fixed`
> Fix snappy block reader

- fastavro/_logical_writers.pyx
- fastavro/_logical_writers_py.py
- fastavro/_read.pyx
- fastavro/_read_py.py
- fastavro/_six.pyx
- fastavro/six.py
- tests/test_logical_types.py
Hi, 
this is a fix of decimal serialization and deserialization. It is also about 2x faster than the original implementation.
It is related to https://github.com/fastavro/fastavro/pull/360.
I think the serialization of fixed bytes in `prepare_fixed_decimal` can be also simplified. It will follow in another PR.
Best regards
> Fixed decimal serialization and deserialization

- fastavro/_read.pyx
- fastavro/_read_py.py
Hello,
performance of `fastavro` is critical to us because we are using `avro` as the main transport protocol. It seems that serialization/deserialization is our bottleneck right now. I profiled the code a little and noticed that `read_decimal` takes substantial time (we use decimal a lot). So this is my attempt to improve the speed. I used a pre-made `decimal_context` because the context manager is too demanding. This made the function twice faster.
I also noticed that `extract_record_type` and `extract_logical_type` is called a lot. I didn't find a way how to speed up `extract_record_type` but at least I moved `extract_logical_type` to the branch where it is really needed and saves a few useless calls.
This is just a minor change but improved the speed of decoding on my data (array of …
> Optimize read - decimal, logical type

- .gitignore
- MANIFEST.in
- README.md
- fastavro/_logical_writers.pyx
- fastavro/_logical_writers_py.py
- fastavro/_read.pyx
- fastavro/_read_py.py
- fastavro/_timezone.py
- run-tests.cmd
- tests/test_logical_types.py
Works fine on Windows and Python 3.7. There is still an issue with 2.7, when it hits https://github.com/fastavro/fastavro/blob/master/fastavro/_logical_writers.pyx#L41 - which would need a similar fix. We don't support 2.7 anymore, though, so would prefer to fix separately to avoid risk.
Tested successfully on Linux and Python 2.7 and 3.7.
It does feel a bit awkward, so happy to discuss if you see any improvements.
> pre-epoch timestamps on windows

- run-tests.sh
This `PR` allows to run specific tests, by default run all tests
```bash
./run-tests.sh
./run-tests.sh tests/test_compression.py::test_optional_codecs
```
> fix: allow run pytests with arguments.

- fastavro/io/parser.py
- tests/test_json.py
- Add a check for known schema types to `parser.py`.
- Add a test to `test_json.py` that tests writing a record to json with a schema that includes a dependency on another known schema.
> fix error writing json with dependent schemas (#418)

- Makefile
This looks to be a trivial oversight from a refactoring, as far as I can tell.
> Add missing fastavro/_logical_writers.c to Makefile

- tests/conftest.py
I've been working on adding several features to fastavro (more PRs to come) and encountered a couple minor inconveniences.
The teardown was failing with AttributeError on captured.err. Not sure why, but treating it as a tuple fixed the problem.
The pandas change is just a quality of life improvement, skipping instead of failing the test for optional functionality.
> Minor testing tweaks

- fastavro/_write.pyx
The current logic appears to have an issue with cython build under python3.4, or at least python3.4 on centos 7, which is the only place I tested it.
To reproduce the current problem, build a wheel package with python3.4:
```sh
FASTAVRO_USE_CYTHON=1 python3.4 setup.py bdist_wheel
```
Then install that package. Not sure if the force is needed, I include it to be sure.
```sh
python3.4 -m pip install --upgrade --force-reinstall dist/fastavro-0.23.3-cp34-cp34m-linux_x86_64.whl
```
From a *directory other than the repository root*, try to import the fastavro package.
```sh
python3.4 -c 'import fastavro'
File "<string>", line 1, in <module>
File "/usr/lib64/python3.4/site-packages/fastavro/__init__.py", line 48, in <module>
import fastavro.write
File …
```
> Redo import logic for optional *_write_block functions

- fastavro/_write.pyx
- tests/test_complex.py
In particular, I was trying to write tuples as arrays (the closest avro type).
Writing tuples (or any iterable) as an array already works in the pure python implementation, this makes the cython behavior in line with the python behavior.
P.S. I am implementing [Avro-RPC](https://gitlab.com/yaq/yaqd-core-python/-/tree/avro/yaqd_core/avrorpc) (and protocol reading #424 on top of fastavro). Currently still in early stages, not 100% standard compliant. I also use some 3.7+ features in my current implementation, but would be willing to clean it up/make it work on fastavro supported pythons once I have the finish the implementation.
> Convert iterables to list in cython array writing

- fastavro/_six.pyx
- fastavro/_write.pyx
- fastavro/_write_py.py
- fastavro/six.py
- tests/test_fastavro.py
This PR adds field names to the exception message raised when a value mismatches the type defined in the schema.
The objective is helping to figure out what column has a wrong/corrupted value or type when a `TypeError` or a `ValueError` is raised.
This is particularly useful when writing huge datasets with thousands of rows, dozen of columns and many null/None values in the source data.
Resolves https://github.com/fastavro/fastavro/issues/439
> show fieldname on errors of mismatched types and values

- benchmark/timeit_benchmark.py
- fastavro/_validation.pyx
- fastavro/_validation_py.py
- fastavro/_write.pyx
- tests/test_complex.py
- tests/test_types.py
First of all, sorry for adding too many items in one PR.  They're well separated in commits, so I can easily drop one or more parts.
As a second remark, I should probably add I have no experience with cython, so I'll be happy to read your comments.
The first change allows for python's `array.array` to be serialized to an array.
The second change allows for a `bytearray` to be serialized to bytes.  I had to move some logic to `write_utf8` to avoid performance loss.
The last commit introduces a small change in `write_int`, that improves cython performance for me.
I also added a `timeit`-based benchmark, to easily follow up the effects:
original:
```
Array from list                   100 records, best of   1000
========================================================
write fastavro …
```
> Add array.array to array, bytearray to bytes and write_int improvement

- fastavro/__main__.py
- fastavro/_six.pyx
- fastavro/six.py
- tests/test_logical_types.py
Sorry for getting back so fast, as you can tell I'm looking at binary data.
The output of `bytes` was missing for the standalone `fastavro` command.
Extending `JSONEncoder` also simplifies the code a bit.
> allow bytes in standalone fastavro output

- setup.py
From your changelog seems like in the latest version you dropped Python 2 support but it is incomplete.  You need to set `python_requires` in your setup.py that will prevent users with Python 2.7 from downloading a sdist version they cannot build.
Note: supporting python_requires requires setuptools>=24.2.0 and pip>=9.0.0 to benefit from it.
Details here: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
> Set python_requires='>=3.5'

- fastavro/_write.pyx
- fastavro/_write_py.py
- tests/test_logical_types.py
Previously validate would pass (and it does the prepare step) but then the datum was still pre preparation when it tried to do anything further. 
As far as I can tell this only really matters for record types, but made more general in case there was an edge case I was missing. 
The provided test shows this for an ndarray record type which would fail because set(ndarray) does not work [well, it actually does for 1D arrays, but not 2+ dimensional arrays... even in the 1d case it was doing something funky that technically worked, but only on accident]
> Apply logical type preparation when checking for best union type

- fastavro/_read.pyx
- fastavro/_read_py.py
- tests/test_compression.py
The zstandard stream API produces zstd frames that don't contain the
uncompressed frame size. `zstd.ZstdDecompressor().decompress(data)` is not able to decompress these frames:
```
~>  python
Python 3.9.7 (default, Oct 10 2021, 15:13:22)
>>> import zstandard as zstd
>>> data = b"(\265/\375\x00X)\x00\x00\bAAAA"
>>> zstd.ZstdDecompressor().decompress(data)
File "<stdin>", line 1, in <module>
zstd.ZstdError: could not determine content size in frame header
```
The stream-API, however, works:
```
>>> obj = zstd.ZstdDecompressor().decompressobj()
>>> obj.decompress(data)
b'\x08AAAA'
```
I cannot find a reference to streaming APIs vs non-streaming APIs in
the Avro specification, and I suppose the intention is to support
both. The official `avro` for Python …
> allow decompressing zstandard stream blocks

- fastavro/_read.pyx
- fastavro/_read_py.py
- fastavro/io/binary_decoder.py
- tests/test_fastavro.py
If an incomplete Avro byte sequence is provided for certain types, namely `bytes`, `string` and `fixed`, 
fastavro will return the truncated version rather than erroring indicating the failure.
This is a problem if for instance the Avro bytes are being transmitted over a network that may have momentary lag that provides incomplete records and requires retrying parsing once additional data is available.
Specifically:
```python
>>> from io import BytesIO
>>> file = BytesIO(b"\x0a123")
>>> fastavro.schemaless_reader(file, "string")
```
This represents a string which claims to be 5 bytes long (0x0a in avro's integer format), but only provides 3 bytes.
Existing fastavro will return `"123"`, leaving bytes still in transit out.
Apache's reference python implementation does have a custom …
> Raise EOFError for truncated bytes and fixed data (and transitively strings)

- fastavro/_schema.pyx
- fastavro/_schema_py.py
- tests/test_schema.py
Resolves #727.
`re.match` would return a match if the beginning of the string matched the regex pattern. This allowed ill-formed symbols to pass validation if the beginning of the string complied with the Avro spec. `re.fullmatch` only returns a match if the entire string matches the regex pattern, which yields behavior in line with the Avro spec.
Additionally, note that invoking the `fullmatch` method from a compiled pattern runs approximately 3.6x faster than invoking `fullmatch` from the `re` package and passing the compiled pattern as a parameter. This is likely negligible in the grand scheme of things, but we might as well opt for the faster approach.
Simple benchmark script used to ascertain those results:
```python
import re
import timeit
if __name__ == '__main__':
symbol = …
```
> Update enum symbol validation to enforce avro spec on the entire symbol

- tests/test_main_cli.py
The __main__.py file is executed via `python -m fastavro`.
Users don't execute `__main__.py` directly anyway.
When the file is executed by its path,
the directory containing it is prepended to sys.path by default (unless $PYTHONSAFEPATH is set or `python -P` is used).
When the fastavro directory is first sys.path,
`import types` imports fastvaro/types.py
rather than the standard library types module.
This leads to problems:
File ".../fastavro/fastavro/__main__.py", line 3, in <module>
import json
File "/usr/lib64/python3.12/json/__init__.py", line 106, in <module>
from .decoder import JSONDecoder, JSONDecodeError
File "/usr/lib64/python3.12/json/decoder.py", line 3, in <module>
import re
File "/usr/lib64/python3.12/re/__init__.py", line 124, in <module> …
> Don't run `python .../fastavro/__main__.py` in tests

- fastavro/_schema.pyx
- fastavro/_schema_py.py
- tests/test_schema.py
Since the Java reference implementation no longer enforces the requirement that the default value be the first type in a union, drop this requirement from fastavro as well.  This restores the ability to read data written with fastavro <1.7, while still checking that the default is (or is convertible to) one of the union types. Along the way, refactor the special cases for double and float so that they do not raise exceptions.
Fixes #723
> Allow arbitrary ordering of union fields

- fastavro/utils.py
- tests/test_utils.py
The utility functions utils.generate_many and utils.generate_one currently do not consider the logical types. This means for a `string` field with logical type `uuid` invalid values may be generated.
fastavro will then refuse to encode these values. This prevents users to generate random avro records if their schema contains `uuid` fields. To fix this i added a test and basic implementation for all logical types supported by fastavro.
> consider the logical type when generating random data

- fastavro/_schema.pyx
- fastavro/_schema_py.py
Hey,
I was working on fixing [python-schema-registry-client](https://github.com/marcosschroh/python-schema-registry-client) bump to fastavro 1.9.3 and due typing issue I end up here reading the code source, I found the following code block can be simplified.
Code behavior should not change via this PR.
_I read the Contributing part and I think this change could go straight to a PR. If you mind differently don't hesitate to tell me_
> style: simplify condition in _parse_schema method

- fastavro/_read.pyx
- fastavro/_read_py.py
- tests/test_aliases.py
These changes should fix a issue with the `return_record_name` and `return_named_type` reader options that occur during schema resolution in a union with aliases.
The issue is that if:
- `return_record_name` is set to True
- or `return_named_type` is set to True
one would expect that the returned names are the names from the reader schema. But this is currently not the case when:
- the writer schema has a union where one of the branches is a named record
- the reader schema changes the name of that record and also adds a alias for the old name
**Then the record name of writer schema is returned**. 
This causes some issues like:
- no being able to re-encode the message with the reader schema (the reader schema has no record with the old name)
- having to check the old and new name in code
> fix return_record_name option for aliases in a union

- fastavro/_write.pyx
- fastavro/_write_py.py
- tests/test_fastavro.py
When a union is handed a named schema reference to write, it does not resolve named schemas, and may use an empty set to disambiguate, causing it to select the first type rather than the correct type.
> Resolve referenced schema to disambiguate union types with named schemas

- fastavro/_schema.pyx
- fastavro/_schema_py.py
The keyword argument 'namespace' has a default value. Cython translates the header function into the following C code to handle optional arguments with a default value:
```
/* "fastavro/_schema.pyx":561
* 
* 
* cdef _inject_schema(outer_schema, inner_schema, namespace="", is_injected=False):             # <<<<<<<<<<<<<<
*     # Once injected, we can stop checking to see if we need to inject since it
*     # should only be done once at most
*/
struct __pyx_opt_args_8fastavro_7_schema__inject_schema {
int __pyx_n;
PyObject *namespace;
PyObject *is_injected;
};
...
```
The  `PyObject *namespace;` causes compiler errors if an extension is built with a C++ compiler. My PR  offers a workaround to avoid that collision. 
Also asked about this in[ cython-users …
> Rename the argument with a default value in an internal helper.

- docs/logical_types.rst
Add an explicit type check to the custom logical type encoder examples to demonstrate how to write them so that they will work in union types.
> Docs: custom logical type encoder best practice

- README.md
- benchmark/benchmark.py
**1. Replaced sum(times) / runs with statistics.mean(times)**
_Why?_
1. **Readability**: statistics.mean(times) is more explicit and clearly conveys that we are calculating the mean.
2. **Robustness**: Using sum(times) / runs manually requires ensuring runs is never 0, whereas statistics.mean() handles empty lists gracefully by raising a StatisticsError, which is more informative for debugging.
3. **Extensibility**: statistics provides other statistical functions (median, variance, standard deviation), which can be easily integrated in the future.
**2. Added .6f Formatting for Floating-Point Precision**
_Why?_
1. Ensures consistent output format for easier comparison across different test cases.
2. Limits unnecessary decimal places, preventing excessive precision that doesn’t add value. …
> Refactor timing calculations using statistics.mean() 

- fastavro/_read.pyx
- fastavro/_read_py.py
I observered a big slowdown when using a different writer and reader schema compared to writer schema == reader schema. 
This can be reproduced with this script:
```python
import io
import random
import time
from contextlib import contextmanager
import fastavro
import fastavro.utils
print(fastavro)
def generate_big_schema(field_count):
def field_nr(nr: int):
return {
"name": f"field_{nr}",
"type": "int",
"default": field_count,
"doc": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"
}
return {
"type": "record",
"name": "BigSchema",
"fields": [field_nr(nr) for nr in range(field_count)]
}
WRITER_SCHEMA = fastavro.schema.parse_schema(generate_big_schema(100))
READER_SCHEMA = …
```
> Improve performance for schema resolution
